import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "react-phone-number-input/style.css";
import { ModalProvider } from "@/components/providers/modal-poviders";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnarToaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${font.className} bg-[#ECF0F1] dark:bg-[#313338]`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="dicord-theme"
          >
            <ModalProvider />
            {children}
            <Toaster />
            <SonnarToaster position="bottom-left" />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
