export const countryOptions = [
  { value: "AF", code: "AFG", label: "Afghanistan", number: "004" },
  { value: "AL", code: "ALB", label: "Albania", number: "008" },
  { value: "DZ", code: "DZA", label: "Algeria", number: "012" },
  { value: "AS", code: "ASM", label: "American Samoa", number: "016" },
  { value: "AD", code: "AND", label: "Andorra", number: "020" },
  { value: "AO", code: "AGO", label: "Angola", number: "024" },
  { value: "AI", code: "AIA", label: "Anguilla", number: "660" },
  { value: "AQ", code: "ATA", label: "Antarctica", number: "010" },
  { value: "AG", code: "ATG", label: "Antigua and Barbuda", number: "028" },
  { value: "AR", code: "ARG", label: "Argentina", number: "032" },
  { value: "AM", code: "ARM", label: "Armenia", number: "051" },
  { value: "AW", code: "ABW", label: "Aruba", number: "533" },
  { value: "AU", code: "AUS", label: "Australia", number: "036" },
  { value: "AT", code: "AUT", label: "Austria", number: "040" },
  { value: "AZ", code: "AZE", label: "Azerbaijan", number: "031" },
  { value: "BS", code: "BHS", label: "Bahamas (the)", number: "044" },
  { value: "BH", code: "BHR", label: "Bahrain", number: "048" },
  { value: "BD", code: "BGD", label: "Bangladesh", number: "050" },
  { value: "BB", code: "BRB", label: "Barbados", number: "052" },
  { value: "BY", code: "BLR", label: "Belarus", number: "112" },
  { value: "BE", code: "BEL", label: "Belgium", number: "056" },
  { value: "BZ", code: "BLZ", label: "Belize", number: "084" },
  { value: "BJ", code: "BEN", label: "Benin", number: "204" },
  { value: "BM", code: "BMU", label: "Bermuda", number: "060" },
  { value: "BT", code: "BTN", label: "Bhutan", number: "064" },
  {
    value: "BO",
    code: "BOL",
    label: "Bolivia (Plurinational State of)",
    number: "068",
  },
  {
    value: "BQ",
    code: "BES",
    label: "Bonaire, Sint Eustatius and Saba",
    number: "535",
  },
  { value: "BA", code: "BIH", label: "Bosnia and Herzegovina", number: "070" },
  { value: "BW", code: "BWA", label: "Botswana", number: "072" },
  { value: "BV", code: "BVT", label: "Bouvet Island", number: "074" },
  { value: "BR", code: "BRA", label: "Brazil", number: "076" },
  {
    value: "IO",
    code: "IOT",
    label: "British Indian Ocean Territory (the)",
    number: "086",
  },
  { value: "BN", code: "BRN", label: "Brunei Darussalam", number: "096" },
  { value: "BG", code: "BGR", label: "Bulgaria", number: "100" },
  { value: "BF", code: "BFA", label: "Burkina Faso", number: "854" },
  { value: "BI", code: "BDI", label: "Burundi", number: "108" },
  { value: "CV", code: "CPV", label: "Cabo Verde", number: "132" },
  { value: "KH", code: "KHM", label: "Cambodia", number: "116" },
  { value: "CM", code: "CMR", label: "Cameroon", number: "120" },
  { value: "CA", code: "CAN", label: "Canada", number: "124" },
  { value: "KY", code: "CYM", label: "Cayman Islands (the)", number: "136" },
  {
    value: "CF",
    code: "CAF",
    label: "Central African Republic (the)",
    number: "140",
  },
  { value: "TD", code: "TCD", label: "Chad", number: "148" },
  { value: "CL", code: "CHL", label: "Chile", number: "152" },
  { value: "CN", code: "CHN", label: "China", number: "156" },
  { value: "CX", code: "CXR", label: "Christmas Island", number: "162" },
  {
    value: "CC",
    code: "CCK",
    label: "Cocos (Keeling) Islands (the)",
    number: "166",
  },
  { value: "CO", code: "COL", label: "Colombia", number: "170" },
  { value: "KM", code: "COM", label: "Comoros (the)", number: "174" },
  {
    value: "CD",
    code: "COD",
    label: "Congo (the Democratic Republic of the)",
    number: "180",
  },
  { value: "CG", code: "COG", label: "Congo (the)", number: "178" },
  { value: "CK", code: "COK", label: "Cook Islands (the)", number: "184" },
  { value: "CR", code: "CRI", label: "Costa Rica", number: "188" },
  { value: "HR", code: "HRV", label: "Croatia", number: "191" },
  { value: "CU", code: "CUB", label: "Cuba", number: "192" },
  { value: "CW", code: "CUW", label: "Curaçao", number: "531" },
  { value: "CY", code: "CYP", label: "Cyprus", number: "196" },
  { value: "CZ", code: "CZE", label: "Czechia", number: "203" },
  { value: "DK", code: "DNK", label: "Denmark", number: "208" },
  { value: "DJ", code: "DJI", label: "Djibouti", number: "262" },
  { value: "DM", code: "DMA", label: "Dominica", number: "212" },
  {
    value: "DO",
    code: "DOM",
    label: "Dominican Republic (the)",
    number: "214",
  },
  { value: "EC", code: "ECU", label: "Ecuador", number: "218" },
  { value: "EG", code: "EGY", label: "Egypt", number: "818" },
  { value: "SV", code: "SLV", label: "El Salvador", number: "222" },
  { value: "GQ", code: "GNQ", label: "Equatorial Guinea", number: "226" },
  { value: "ER", code: "ERI", label: "Eritrea", number: "232" },
  { value: "EE", code: "EST", label: "Estonia", number: "233" },
  { value: "SZ", code: "SWZ", label: "Eswatini", number: "748" },
  { value: "ET", code: "ETH", label: "Ethiopia", number: "231" },
  {
    value: "FK",
    code: "FLK",
    label: "Falkland Islands (the) [Malvinas]",
    number: "238",
  },
  { value: "FO", code: "FRO", label: "Faroe Islands (the)", number: "234" },
  { value: "FJ", code: "FJI", label: "Fiji", number: "242" },
  { value: "FI", code: "FIN", label: "Finland", number: "246" },
  { value: "FR", code: "FRA", label: "France", number: "250" },
  { value: "GF", code: "GUF", label: "French Guiana", number: "254" },
  { value: "PF", code: "PYF", label: "French Polynesia", number: "258" },
  {
    value: "TF",
    code: "ATF",
    label: "French Southern Territories (the)",
    number: "260",
  },
  { value: "GA", code: "GAB", label: "Gabon", number: "266" },
  { value: "GM", code: "GMB", label: "Gambia (the)", number: "270" },
  { value: "GE", code: "GEO", label: "Georgia", number: "268" },
  { value: "DE", code: "DEU", label: "Germany", number: "276" },
  { value: "GH", code: "GHA", label: "Ghana", number: "288" },
  { value: "GI", code: "GIB", label: "Gibraltar", number: "292" },
  { value: "GR", code: "GRC", label: "Greece", number: "300" },
  { value: "GL", code: "GRL", label: "Greenland", number: "304" },
  { value: "GD", code: "GRD", label: "Grenada", number: "308" },
  { value: "GP", code: "GLP", label: "Guadeloupe", number: "312" },
  { value: "GU", code: "GUM", label: "Guam", number: "316" },
  { value: "GT", code: "GTM", label: "Guatemala", number: "320" },
  { value: "GG", code: "GGY", label: "Guernsey", number: "831" },
  { value: "GN", code: "GIN", label: "Guinea", number: "324" },
  { value: "GW", code: "GNB", label: "Guinea-Bissau", number: "624" },
  { value: "GY", code: "GUY", label: "Guyana", number: "328" },
  { value: "HT", code: "HTI", label: "Haiti", number: "332" },
  {
    value: "HM",
    code: "HMD",
    label: "Heard Island and McDonald Islands",
    number: "334",
  },
  { value: "VA", code: "VAT", label: "Holy See (the)", number: "336" },
  { value: "HN", code: "HND", label: "Honduras", number: "340" },
  { value: "HK", code: "HKG", label: "Hong Kong", number: "344" },
  { value: "HU", code: "HUN", label: "Hungary", number: "348" },
  { value: "IS", code: "ISL", label: "Iceland", number: "352" },
  { value: "IN", code: "IND", label: "India", number: "356" },
  { value: "ID", code: "IDN", label: "Indonesia", number: "360" },
  {
    value: "IR",
    code: "IRN",
    label: "Iran (Islamic Republic of)",
    number: "364",
  },
  { value: "IQ", code: "IRQ", label: "Iraq", number: "368" },
  { value: "IE", code: "IRL", label: "Ireland", number: "372" },
  { value: "IM", code: "IMN", label: "Isle of Man", number: "833" },
  { value: "IL", code: "ISR", label: "Israel", number: "376" },
  { value: "IT", code: "ITA", label: "Italy", number: "380" },
  { value: "CI", code: "CIV", label: "Ivory Coast", number: "384" },
  { value: "JM", code: "JAM", label: "Jamaica", number: "388" },
  { value: "JP", code: "JPN", label: "Japan", number: "392" },
  { value: "JE", code: "JEY", label: "Jersey", number: "832" },
  { value: "JO", code: "JOR", label: "Jordan", number: "400" },
  { value: "KZ", code: "KAZ", label: "Kazakhstan", number: "398" },
  { value: "KE", code: "KEN", label: "Kenya", number: "404" },
  { value: "KI", code: "KIR", label: "Kiribati", number: "296" },
  {
    value: "KP",
    code: "PRK",
    label: "Korea (the Democratic People's Republic of)",
    number: "408",
  },
  {
    value: "KR",
    code: "KOR",
    label: "Korea (the Republic of)",
    number: "410",
  },
  { value: "KW", code: "KWT", label: "Kuwait", number: "414" },
  { value: "KG", code: "KGZ", label: "Kyrgyzstan", number: "417" },
  {
    value: "LA",
    code: "LAO",
    label: "Lao People's Democratic Republic (the)",
    number: "418",
  },
  { value: "LV", code: "LVA", label: "Latvia", number: "428" },
  { value: "LB", code: "LBN", label: "Lebanon", number: "422" },
  { value: "LS", code: "LSO", label: "Lesotho", number: "426" },
  { value: "LR", code: "LBR", label: "Liberia", number: "430" },
  { value: "LY", code: "LBY", label: "Libya", number: "434" },
  { value: "LI", code: "LIE", label: "Liechtenstein", number: "438" },
  { value: "LT", code: "LTU", label: "Lithuania", number: "440" },
  { value: "LU", code: "LUX", label: "Luxembourg", number: "442" },
  { value: "MO", code: "MAC", label: "Macao", number: "446" },
  { value: "MG", code: "MDG", label: "Madagascar", number: "450" },
  { value: "MW", code: "MWI", label: "Malawi", number: "454" },
  { value: "MY", code: "MYS", label: "Malaysia", number: "458" },
  { value: "MV", code: "MDV", label: "Maldives", number: "462" },
  { value: "ML", code: "MLI", label: "Mali", number: "466" },
  { value: "MT", code: "MLT", label: "Malta", number: "470" },
  { value: "MH", code: "MHL", label: "Marshall Islands (the)", number: "584" },
  { value: "MQ", code: "MTQ", label: "Martinique", number: "474" },
  { value: "MR", code: "MRT", label: "Mauritania", number: "478" },
  { value: "MU", code: "MUS", label: "Mauritius", number: "480" },
  { value: "YT", code: "MYT", label: "Mayotte", number: "175" },
  { value: "MX", code: "MEX", label: "Mexico", number: "484" },
  {
    value: "FM",
    code: "FSM",
    label: "Micronesia (Federated States of)",
    number: "583",
  },
  {
    value: "MD",
    code: "MDA",
    label: "Moldova (the Republic of)",
    number: "498",
  },
  { value: "MC", code: "MCO", label: "Monaco", number: "492" },
  { value: "MN", code: "MNG", label: "Mongolia", number: "496" },
  { value: "ME", code: "MNE", label: "Montenegro", number: "499" },
  { value: "MS", code: "MSR", label: "Montserrat", number: "500" },
  { value: "MA", code: "MAR", label: "Morocco", number: "504" },
  { value: "MZ", code: "MOZ", label: "Mozambique", number: "508" },
  { value: "MM", code: "MMR", label: "Myanmar", number: "104" },
  { value: "NA", code: "NAM", label: "Namibia", number: "516" },
  { value: "NR", code: "NRU", label: "Nauru", number: "520" },
  { value: "NP", code: "NPL", label: "Nepal", number: "524" },
  { value: "NL", code: "NLD", label: "Netherlands (the)", number: "528" },
  { value: "NC", code: "NCL", label: "New Caledonia", number: "540" },
  { value: "NZ", code: "NZL", label: "New Zealand", number: "554" },
  { value: "NI", code: "NIC", label: "Nicaragua", number: "558" },
  { value: "NE", code: "NER", label: "Niger (the)", number: "562" },
  { value: "NG", code: "NGA", label: "Nigeria", number: "566" },
  { value: "NU", code: "NIU", label: "Niue", number: "570" },
  { value: "NF", code: "NFK", label: "Norfolk Island", number: "574" },
  {
    value: "MP",
    code: "MNP",
    label: "Northern Mariana Islands (the)",
    number: "580",
  },
  { value: "NO", code: "NOR", label: "Norway", number: "578" },
  { value: "OM", code: "OMN", label: "Oman", number: "512" },
  { value: "PK", code: "PAK", label: "Pakistan", number: "586" },
  { value: "PW", code: "PLW", label: "Palau", number: "585" },
  { value: "PS", code: "PSE", label: "Palestine, State of", number: "275" },
  { value: "PA", code: "PAN", label: "Panama", number: "591" },
  { value: "PG", code: "PNG", label: "Papua New Guinea", number: "598" },
  { value: "PY", code: "PRY", label: "Paraguay", number: "600" },
  { value: "PE", code: "PER", label: "Peru", number: "604" },
  { value: "PH", code: "PHL", label: "Philippines (the)", number: "608" },
  { value: "PN", code: "PCN", label: "Pitcairn", number: "612" },
  { value: "PL", code: "POL", label: "Poland", number: "616" },
  { value: "PT", code: "PRT", label: "Portugal", number: "620" },
  { value: "PR", code: "PRI", label: "Puerto Rico", number: "630" },
  { value: "QA", code: "QAT", label: "Qatar", number: "634" },
  {
    value: "MK",
    code: "MKD",
    label: "Republic of North Macedonia",
    number: "807",
  },
  { value: "RO", code: "ROU", label: "Romania", number: "642" },
  {
    value: "RU",
    code: "RUS",
    label: "Russian Federation (the)",
    number: "643",
  },
  { value: "RW", code: "RWA", label: "Rwanda", number: "646" },
  { value: "RE", code: "REU", label: "Réunion", number: "638" },
  { value: "BL", code: "BLM", label: "Saint Barthélemy", number: "652" },
  {
    value: "SH",
    code: "SHN",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    number: "654",
  },
  { value: "KN", code: "KNA", label: "Saint Kitts and Nevis", number: "659" },
  { value: "LC", code: "LCA", label: "Saint Lucia", number: "662" },
  {
    value: "MF",
    code: "MAF",
    label: "Saint Martin (French part)",
    number: "663",
  },
  {
    value: "PM",
    code: "SPM",
    label: "Saint Pierre and Miquelon",
    number: "666",
  },
  {
    value: "VC",
    code: "VCT",
    label: "Saint Vincent and the Grenadines",
    number: "670",
  },
  { value: "WS", code: "WSM", label: "Samoa", number: "882" },
  { value: "SM", code: "SMR", label: "San Marino", number: "674" },
  { value: "ST", code: "STP", label: "Sao Tome and Principe", number: "678" },
  { value: "SA", code: "SAU", label: "Saudi Arabia", number: "682" },
  { value: "SN", code: "SEN", label: "Senegal", number: "686" },
  { value: "RS", code: "SRB", label: "Serbia", number: "688" },
  { value: "SC", code: "SYC", label: "Seychelles", number: "690" },
  { value: "SL", code: "SLE", label: "Sierra Leone", number: "694" },
  { value: "SG", code: "SGP", label: "Singapore", number: "702" },
  {
    value: "SX",
    code: "SXM",
    label: "Sint Maarten (Dutch part)",
    number: "534",
  },
  { value: "SK", code: "SVK", label: "Slovakia", number: "703" },
  { value: "SI", code: "SVN", label: "Slovenia", number: "705" },
  { value: "SB", code: "SLB", label: "Solomon Islands", number: "090" },
  { value: "SO", code: "SOM", label: "Somalia", number: "706" },
  { value: "ZA", code: "ZAF", label: "South Africa", number: "710" },
  {
    value: "GS",
    code: "SGS",
    label: "South Georgia and the South Sandwich Islands",
    number: "239",
  },
  { value: "SS", code: "SSD", label: "South Sudan", number: "728" },
  { value: "ES", code: "ESP", label: "Spain", number: "724" },
  { value: "LK", code: "LKA", label: "Sri Lanka", number: "144" },
  { value: "SD", code: "SDN", label: "Sudan (the)", number: "729" },
  { value: "SR", code: "SUR", label: "Suriname", number: "740" },
  { value: "SJ", code: "SJM", label: "Svalbard and Jan Mayen", number: "744" },
  { value: "SE", code: "SWE", label: "Sweden", number: "752" },
  { value: "CH", code: "CHE", label: "Switzerland", number: "756" },
  { value: "SY", code: "SYR", label: "Syrian Arab Republic", number: "760" },
  { value: "TW", code: "TWN", label: "Taiwan", number: "158" },
  { value: "TJ", code: "TJK", label: "Tajikistan", number: "762" },
  {
    value: "TZ",
    code: "TZA",
    label: "Tanzania, United Republic of",
    number: "834",
  },
  { value: "TH", code: "THA", label: "Thailand", number: "764" },
  { value: "TL", code: "TLS", label: "Timor-Leste", number: "626" },
  { value: "TG", code: "TGO", label: "Togo", number: "768" },
  { value: "TK", code: "TKL", label: "Tokelau", number: "772" },
  { value: "TO", code: "TON", label: "Tonga", number: "776" },
  { value: "TT", code: "TTO", label: "Trinidad and Tobago", number: "780" },
  { value: "TN", code: "TUN", label: "Tunisia", number: "788" },
  { value: "TR", code: "TUR", label: "Turkey", number: "792" },
  { value: "TM", code: "TKM", label: "Turkmenistan", number: "795" },
  {
    value: "TC",
    code: "TCA",
    label: "Turks and Caicos Islands (the)",
    number: "796",
  },
  { value: "TV", code: "TUV", label: "Tuvalu", number: "798" },
  { value: "UG", code: "UGA", label: "Uganda", number: "800" },
  { value: "UA", code: "UKR", label: "Ukraine", number: "804" },
  {
    value: "AE",
    code: "ARE",
    label: "United Arab Emirates (the)",
    number: "784",
  },
  {
    value: "GB",
    code: "GBR",
    label: "United Kingdom of Great Britain and Northern Ireland (the)",
    number: "826",
  },
  {
    value: "UM",
    code: "UMI",
    label: "United States Minor Outlying Islands (the)",
    number: "581",
  },
  {
    value: "US",
    code: "USA",
    label: "United States of America (the)",
    number: "840",
  },
  { value: "UY", code: "URY", label: "Uruguay", number: "858" },
  { value: "UZ", code: "UZB", label: "Uzbekistan", number: "860" },
  { value: "VU", code: "VUT", label: "Vanuatu", number: "548" },
  {
    value: "VE",
    code: "VEN",
    label: "Venezuela (Bolivarian Republic of)",
    number: "862",
  },
  { value: "VN", code: "VNM", label: "Viet Nam", number: "704" },
  {
    value: "VG",
    code: "VGB",
    label: "Virgin Islands (British)",
    number: "092",
  },
  { value: "VI", code: "VIR", label: "Virgin Islands (U.S.)", number: "850" },
  { value: "WF", code: "WLF", label: "Wallis and Futuna", number: "876" },
  { value: "EH", code: "ESH", label: "Western Sahara", number: "732" },
  { value: "YE", code: "YEM", label: "Yemen", number: "887" },
  { value: "ZM", code: "ZMB", label: "Zambia", number: "894" },
  { value: "ZW", code: "ZWE", label: "Zimbabwe", number: "716" },
  { value: "AX", code: "ALA", label: "Åland Islands", number: "248" },
];
